export const storeProducts = [{
    id: 1,
    title: "Lorem ipsum dolor",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 100,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: true,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}, {
    id: 2,
    title: "Omet offal butcher",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 160,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}, {
    id: 3,
    title: "Offal butcher quino",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 800,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}, {
    id: 4,
    title: "Dolor amet offal",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 180,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}, {
    id: 5,
    title: "Quinoa sustainable ",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 240,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}, {
    id: 6,
    title: "Ipsum gastropub",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 170,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}, {
    id: 7,
    title: "Vustainable sustainable",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 100,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}, {
    id: 8,
    title: "Offal gastropub",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 180,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}, {
    id: 9,
    title: "Offal amet",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 280,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
}];

export const detailProduct = {
    id: 9,
    title: "Sriracha paleo",
    img1: "img/ring.jpg",
    img2: "img/ring.jpg",
    img3: "img/ring.jpg",
    price: 100,
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    material: 'offal ghjfa',
    rock: 'quinof',
    count: 0,
    total: 0
};
